version: "3.9"
services:
  backend:
    build: .
    container_name: backend-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
